# Noise estimators for the FM-DBZP search grid. See the doctrings of
# `OppositeRowNoiseEstimator` and `GlobalMeanNoiseEstimator` for the rationale
# behind picking one or the other; this header is just a quick reference.
#
# `power_bins` layout: (num_doppler_bins, num_code_phase_bins) — rows = Doppler
# bins, columns = code phase bins.
#
# Returns: (signal_power, noise_power, code_phase_bin, doppler_bin)

"""
    AbstractNoiseEstimator

Singleton type marking which noise-power estimator is used by `acquire!`
when computing the CFAR test statistic. Stored in [`AcquisitionPlan`](@ref)
so the choice is fixed at plan-construction time and flows through every
subsequent `acquire!` call.

Pass to [`plan_acquire`](@ref) via the `noise_estimator` keyword:

```julia
plan = plan_acquire(system, sampling_freq, prns;
    noise_estimator = OppositeRowNoiseEstimator())  # default

plan = plan_acquire(system, sampling_freq, prns;
    noise_estimator = GlobalMeanNoiseEstimator())   # alternative
```

See [`OppositeRowNoiseEstimator`](@ref) and [`GlobalMeanNoiseEstimator`](@ref).
"""
abstract type AbstractNoiseEstimator end

"""
    OppositeRowNoiseEstimator()

Default noise estimator. Averages the cells of one Doppler row across all
code-phase columns — specifically the row exactly half the search grid away
from the peak. That single row is then taken as the noise floor estimate.

## Why this is the default

The CFAR test statistic is `peak_power / noise_power`, so a biased noise
estimate translates directly into FP/FN errors. On real-world IF signals
the search-grid noise floor is *not* independent and identically
distributed across Doppler: DC offset, IF spurs and narrowband interferers
inflate specific Doppler rows ("Doppler-conditional banding"). Averaging
over the whole grid then mixes hot rows into the noise estimate, the
threshold rises with the hot rows, and any peak whose Doppler happens to
land in a quiet row passes the inflated threshold — hence false alarms
cluster at specific Doppler offsets.

Estimating the noise from a *single* Doppler row removes that bias: the
estimate is conditioned on Doppler, so the threshold tracks the local noise
floor. The opposite row (peak Doppler bin offset by `num_doppler_bins ÷ 2`)
is the natural choice — it is statistically far from any signal mainlobe and
cannot be contaminated by a real signal's sidelobes either. This mirrors
GNSS-SDR's `pcps_acquisition::max_to_input_power_statistic`.

The downside is a slightly larger variance on the noise estimate than the
global mean (one row of `samples_per_code` cells, vs. the full grid), but
the bias removal dominates: in practice the false-alarm rate on
Doppler-banded signals drops by an order of magnitude or more.

## When to use [`GlobalMeanNoiseEstimator`](@ref) instead

Synthetic AWGN test signals where the noise floor is genuinely flat across
Doppler. The global mean uses ~`num_doppler_bins`× more samples and so has
a tighter (lower-variance) estimate when the noise really is independent
and identically distributed across the grid.
"""
struct OppositeRowNoiseEstimator <: AbstractNoiseEstimator end

"""
    GlobalMeanNoiseEstimator()

Alternative noise estimator. Averages every cell of the search grid except
a small `±samples_per_chip` exclusion zone around the peak column.

This matches the original CFAR formula derivation: when the per-cell noise
power is independent and identically distributed, all `num_cells` are
exchangeable and the unbiased noise-power estimate is the sample mean over
the cells. With a large grid the variance of this estimate is essentially
zero, which makes it the lowest-variance estimator *when that assumption
holds*.

## When to use this

Synthetic AWGN test signals with no Doppler-conditional structure
(generated by [`generate_test_signal`](@ref) with white noise, for example).

## When NOT to use this

Real-world IF recordings. Hardware-induced effects make the noise floor
Doppler-dependent — DC offset, IF spurs, narrowband interferers, ADC
nonlinearity all inflate specific rows of the grid. The global mean folds
those hot rows into the noise estimate, the threshold rises with them, and
peaks landing in quiet rows pass it — producing clusters of false alarms
at predictable Doppler offsets. Prefer [`OppositeRowNoiseEstimator`](@ref)
in that case (it is the default).
"""
struct GlobalMeanNoiseEstimator <: AbstractNoiseEstimator end

# ============================================================================
# Internal helpers
# ============================================================================

# Find the peak (location + value) and accumulate per-column sums in one pass.
# Returns (peak_value, peak_doppler_bin, peak_code_phase_bin).
# col_sums is filled but only used by GlobalMeanNoiseEstimator.
function _findmax_and_colsums!(col_sums::Vector{T}, power_bins::AbstractMatrix{T}) where {T<:AbstractFloat}
    num_doppler_bins, num_code_phase_bins = size(power_bins)
    peak_power          = power_bins[1, 1]
    peak_code_phase_bin = 1
    @inbounds for c in 1:num_code_phase_bins
        col_sum = zero(T)
        col_max = power_bins[1, c]
        @simd for r in 1:num_doppler_bins
            v = power_bins[r, c]
            col_sum += v
            col_max = max(col_max, v)
        end
        col_sums[c] = col_sum
        if col_max > peak_power
            peak_power          = col_max
            peak_code_phase_bin = c
        end
    end
    peak_doppler_bin = 1
    @inbounds for r in 1:num_doppler_bins
        if power_bins[r, peak_code_phase_bin] == peak_power
            peak_doppler_bin = r
            break
        end
    end
    peak_power, peak_doppler_bin, peak_code_phase_bin
end

# Mean over a single Doppler row (no exclusion — used for the opposite row,
# which contains no signal by construction).
function _row_mean(power_bins::AbstractMatrix{T}, row::Int) where {T<:AbstractFloat}
    num_code_phase_bins = size(power_bins, 2)
    s = zero(T)
    @inbounds @simd for c in 1:num_code_phase_bins
        s += power_bins[row, c]
    end
    s / T(num_code_phase_bins)
end

# Original cell-averaging noise estimator over col_sums with ±chip exclusion
# around the peak column.
function _global_mean_from_colsums(
    col_sums::Vector{T},
    num_doppler_bins::Int,
    peak_code_phase_bin::Int,
    samples_per_chip::Int,
) where {T<:AbstractFloat}
    num_code_phase_bins = length(col_sums)
    excl_col_lo   = max(1, peak_code_phase_bin - samples_per_chip)
    excl_col_hi   = min(num_code_phase_bins, peak_code_phase_bin + samples_per_chip)
    num_excl_cols = excl_col_hi - excl_col_lo + 1
    total_power = zero(T)
    excl_power  = zero(T)
    @inbounds for c in 1:num_code_phase_bins
        col_sum = col_sums[c]
        total_power += col_sum
        if excl_col_lo <= c <= excl_col_hi
            excl_power += col_sum
        end
    end
    (total_power - excl_power) / T((num_code_phase_bins - num_excl_cols) * num_doppler_bins)
end

# ============================================================================
# Public API: est_signal_noise_power dispatched by estimator type
# ============================================================================

"""
    est_signal_noise_power(power_bins, sampling_freq, code_freq, col_sums,
                           estimator = OppositeRowNoiseEstimator())

Estimate `(signal_power, noise_power, peak_code_phase_bin, peak_doppler_bin)`
from a noncoherent-integration `power_bins` matrix using the given
[`AbstractNoiseEstimator`](@ref).

`power_bins` is laid out as `(num_doppler_bins, num_code_phase_bins)` —
rows are Doppler bins, columns are code phase bins. The peak is found over
the whole grid; the noise power estimate depends on the chosen estimator.

## Choosing an estimator

The default [`OppositeRowNoiseEstimator`](@ref) averages a single Doppler row
half the search grid away from the peak. This is the right choice for
real-world IF signals, where the noise floor is Doppler-dependent (DC
offset, IF spurs, narrowband interferers each inflate specific Doppler
rows) and a global average folds those hot rows into the noise estimate,
producing false alarms at predictable Doppler offsets.

[`GlobalMeanNoiseEstimator`](@ref) averages all cells with a small
exclusion zone around the peak; lower variance when the noise really is
independent and identically distributed across the grid, but biased on
real signals. Useful for synthetic AWGN tests.

The estimator is normally chosen once via the `noise_estimator` keyword of
[`plan_acquire`](@ref) and then flows through `acquire!`; this lower-level
function is exposed mainly for tests and custom pipelines.

## Arguments

- `col_sums`: length-`samples_per_code` scratch vector. Always written,
  only read by `GlobalMeanNoiseEstimator`.
"""
function est_signal_noise_power(
    power_bins::AbstractMatrix{T},
    sampling_freq,
    code_freq,
    col_sums::Vector{T},
    ::OppositeRowNoiseEstimator = OppositeRowNoiseEstimator(),
) where {T<:AbstractFloat}
    num_doppler_bins = size(power_bins, 1)
    peak_power, peak_doppler_bin, peak_code_phase_bin =
        _findmax_and_colsums!(col_sums, power_bins)
    # Opposite Doppler row, modular wrap. The opposite row is half the grid
    # away — far enough from any signal mainlobe to be noise-only.
    opp_row = mod(peak_doppler_bin - 1 + num_doppler_bins ÷ 2, num_doppler_bins) + 1
    noise_power = _row_mean(power_bins, opp_row)
    signal_power = peak_power - noise_power
    signal_power, noise_power, peak_code_phase_bin, peak_doppler_bin
end

function est_signal_noise_power(
    power_bins::AbstractMatrix{T},
    sampling_freq,
    code_freq,
    col_sums::Vector{T},
    ::GlobalMeanNoiseEstimator,
) where {T<:AbstractFloat}
    samples_per_chip = floor(Int, sampling_freq / code_freq)
    num_doppler_bins = size(power_bins, 1)
    peak_power, peak_doppler_bin, peak_code_phase_bin =
        _findmax_and_colsums!(col_sums, power_bins)
    noise_power = _global_mean_from_colsums(col_sums, num_doppler_bins, peak_code_phase_bin, samples_per_chip)
    signal_power = peak_power - noise_power
    signal_power, noise_power, peak_code_phase_bin, peak_doppler_bin
end
